# Coordinator Development Config
[core]
host = "0.0.0.0"
port = "1337"
log_filter = "info"

[chains]
btc = true
btc_rpc = ""
eth = true
eth_rpc = ""
xmr = true
xmr_rpc = ""

[observer]
host_prefix = "ws://node-"
port = "9944"

[kafka]
host = "kafka"
port = "9092" # localhost connects from 9094, internal docker connects from 9092
offset_reset = "smallest"

[network]
signers = ["alice", "bob", "charlie"]
