version: "3.9"

volumes:
  serai-base:
  serai-alice:
  serai-bob:
  serai-charlie:
  serai-dave:
  serai-eve:
  serai-ferdie:

# Consensus Services
services:

  _serai:
    &serai_defaults
    restart: unless-stopped
    profiles:
      - _
    image: serai/serai:latest
    build:
      context: .
      dockerfile: ./deploy/serai/Dockerfile
      args:
        TAG: serai

  serai-base:
    &serai
    <<: *serai_defaults
    hostname: baseserai
    profiles:
      - base
    ports:
      - 30333
      - 9615
      - 9933
      - 9944

  # Processor Services

  # Coin Services
  bitcoin:
    profiles:
      - single-coins
      - cluster-sm-coins
      - cluster-lg-coins
      - coins
      - bitcoin
    build:
      dockerfile: ./coins/bitcoin/Dockerfile
      context: .
    restart: unless-stopped
    volumes:
      - "./coins/bitcoin/scripts:/scripts"
    entrypoint: /scripts/entry-dev.sh