version: "3.9"


volumes:
  serai-base:
  serai-alice:
  serai-bob:
  serai-charlie:
  serai-dave:
  serai-eve:
  serai-ferdie:

# ------------------------------------------------------------
# Services
# ------------------------------------------------------------
# Profiles:
# base - single node, unidentified
# coins - node clients for coins only (XMR, BTC, ETH)
# cluster-sm - Alice, Bob, Charlie
# cluter-lg - Alice, Bob, Charlie, Dave, Eve, Ferdie
# cluster-coins-sm - cluster-sm with coins
# cluster-coins-lg - cluster-lg with coins
# monero - full node monero only
# bitcoin - full node bitcoin only
# ethereum - full node ethereum only
# Example: docker compose --profile bitcoin up

services:

  _serai:
    &serai_defaults
    restart: unless-stopped
    profiles:
      - _
    build:
      context: ../
      dockerfile: ./deploy/serai/Dockerfile
      args:
        TAG: serai

  serai-base:
    &serai
    <<: *serai_defaults
    hostname: baseserai
    profiles:
      - base
    environment:
      CHAIN: dev
    entrypoint: /scripts/entry-dev.sh
    volumes:
      - "./serai/scripts:/scripts"


  # Processor Services

  # Coin Services
  monero:
    profiles:
      - single-coins
      - cluster-coins-sm
      - cluster-coins-lg
      - coins
      - monero
    build:
      context: ./coins/monero/
    restart: unless-stopped
    volumes:
      - "./coins/monero/temp:/temp"
      - "./coins/monero/scripts:/scripts"
    entrypoint: /scripts/entry-dev.sh

  bitcoin:
    profiles:
      - single-coins
      - cluster-coins-sm
      - cluster-coins-lg
      - coins
      - bitcoin
    build:
      context: ./coins/bitcoin/
    restart: unless-stopped
    volumes:
      - "./coins/bitcoin/scripts:/scripts"
    entrypoint: /scripts/entry-dev.sh

  ethereum:
    profiles:
      - single-coins
      - cluster-coins-sm
      - cluster-coins-lg
      - coins
      - ethereum
    build:
      context: ./coins/ethereum/
    restart: unless-stopped
    volumes:
      - "./coins/ethereum/scripts:/scripts"
    entrypoint: /scripts/entry-dev.sh